apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: true
  artifacts:
    - image: webmakaka/mern-stack-front-to-back-v2-client
      context: ../app/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: webmakaka/mern-stack-front-to-back-v2-api
      context: ../app/api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
